[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[build]
target = "riscv64gc-lp64d.json"
rustflags = ["-C", "force-frame-pointers=yes"]
